<?php
    header('content-type:text/html;charset=utf8');
    $data = array(
        array(
            'img1' => '../images/shop/1-1b.jpg',
            'img2' => '../images/shop/1-2b.jpg',
            'img3' => '../images/shop/1-3b.jpg',
            'img4' => '../images/shop/1-4b.jpg',
            'img5' => '../images/shop/1-5b.jpg',
            'h1' => '【直营】进口Slip眼罩美容亲肤真丝眼罩遮光眼罩睡眠护肤眼罩纯色',
            'h2' =>'明星同款眼罩 真丝眼罩 舒适亲肤',
            'em' =>'398.00',
            'img6' => '../images/shop/1-6b.jpg',
            'img7' => '../images/shop/1-7b.jpg',
            'img8' => '../images/shop/1-8b.jpg',
            'img9' => '../images/shop/1-9b.jpg',
            'img10' => '../images/shop/1-10b.jpg',
            'id' => '0'
        ),
        array(
            'img1' => '../images/shop/2-1.jpg',
            'img2' => '../images/shop/2-2.jpg',
            'img3' => '../images/shop/2-3.jpg',
            'img4' => '../images/shop/2-4.jpg',
            'img5' => '../images/shop/2-5.jpg',
            'h1' => '【直营】进口WPC浪漫蝴蝶结雨伞遮光遮热伞遮阳防晒伞新款日本',
            'h2' =>'防晒涂层遮阳伞 分长柄短柄',
            'em' =>'298.00',
            'img6' => '../images/shop/2-6.jpg',
            'img7' => '../images/shop/2-7.jpg',
            'img8' => '../images/shop/2-8.jpg',
            'img9' => '../images/shop/2-9.jpg',
            'img10' => '../images/shop/2-10.jpg',
            'id' => '1'
        ),
        array(
            'img1' => '../images/shop/3-1.jpg',
            'img2' => '../images/shop/3-2.jpg',
            'img3' => '../images/shop/3-3.jpg',
            'img4' => '../images/shop/3-4.jpg',
            'img5' => '../images/shop/3-5.jpg',
            'h1' => '【直营】爱丽思 日式透明组合鞋盒加厚可叠加鞋盒防尘防潮 3个装',
            'h2' =>'日式风格 可叠加设计 自由组合 环保用料',
            'em' =>'104.00',
            'img6' => '../images/shop/3-1.jpg',
            'img7' => '../images/shop/3-2.jpg',
            'img8' => '../images/shop/3-3.jpg',
            'img9' => '../images/shop/3-4.jpg',
            'img10' => '../images/shop/3-5.jpg',
            'id' => '2'
        ),
        array(
            'img1' => '../images/shop/5-1.jpg',
            'img2' => '../images/shop/5-2.jpg',
            'img3' => '../images/shop/5-3.jpg',
            'img4' => '../images/shop/5-4.jpg',
            'img5' => '../images/shop/5-5.jpg',
            'h1' => '【直营】明星同款 Travel Blue护脖子午睡旅行枕u形颈椎枕 英国',
            'h2' =>'【鹿晗吴磊黄晓明同款】U型枕 双弧护肩',
            'em' =>'496.00',
            'img6' => '../images/shop/5-6.jpg',
            'img7' => '../images/shop/5-7.jpg',
            'img8' => '../images/shop/5-8.jpg',
            'img9' => '../images/shop/5-9.jpg',
            'img10' => '../images/shop/5-10.jpg',
            'id' => '3'
        ),
        array(
            'img1' => '../images/shop/4-1.jpg',
            'img2' => '../images/shop/4-2.jpg',
            'img3' => '../images/shop/4-3.jpg',
            'img4' => '../images/shop/4-4.jpg',
            'img5' => '../images/shop/4-5.jpg',
            'h1' => '【直营】swell进口网红便携式情侣款大容量限量版保温保冷杯500ml',
            'h2' =>'明星同款 来自纽约 长效保冷 轻巧便携',
            'em' =>'425.00',
            'img6' => '../images/shop/4-6.jpg',
            'img7' => '../images/shop/4-8.jpg',
            'img8' => '../images/shop/4-3.jpg',
            'img9' => '../images/shop/4-4.jpg',
            'img10' => '../images/shop/4-5.jpg',
            'id' => '4'
        ),
        array(
            'img1' => '../images/shop/6-1.jpg',
            'img2' => '../images/shop/6-2.jpg',
            'img3' => '../images/shop/6-3.jpg',
            'img4' => '../images/shop/6-4.jpg',
            'img5' => '../images/shop/6-5.jpg',
            'h1' => '【直营】Zojirushi 象印 进口不锈钢真空保温杯 SM-SD48 480ml',
            'h2' =>'明星同款 来自纽约 长效保冷 轻巧便携',
            'em' =>'239.00',
            'img6' => '../images/shop/6-6.jpg',
            'img7' => '../images/shop/6-8.jpg',
            'img8' => '../images/shop/6-3.jpg',
            'img9' => '../images/shop/6-4.jpg',
            'img10' => '../images/shop/6-5.jpg',
            'id' => '5'
        ),
        array(
            'img1' => '../images/shop/8-1.jpg',
            'img2' => '../images/shop/8-2.jpg',
            'img3' => '../images/shop/8-3.jpg',
            'img4' => '../images/shop/8-4.jpg',
            'img5' => '../images/shop/8-5.jpg',
            'h1' => '【直营】乐美雅进口琥珀锅套组1.5L+3L玻璃锅可直烧汤锅蒸锅法国',
            'h2' =>'高颜值安全玻璃锅 可用于明火微波炉烤箱',
            'em' =>'1096.00',
            'img6' => '../images/shop/8-6.jpg',
            'img7' => '../images/shop/8-2.jpg',
            'img8' => '../images/shop/8-3.jpg',
            'img9' => '../images/shop/8-4.jpg',
            'img10' => '../images/shop/8-5.jpg',
            'id' => '6'
        ),
        array(
            'img1' => '../images/shop/7-1.jpg',
            'img2' => '../images/shop/7-2.jpg',
            'img3' => '../images/shop/7-3.jpg',
            'img4' => '../images/shop/7-4.jpg',
            'img5' => '../images/shop/7-5.jpg',
            'h1' => '【直营】highcook韩库进口蓝宝石不粘炒锅无烟电磁炉平底锅30cm',
            'h2' =>'韩国爆款蓝宝石煎炒两用锅 智能控烟真不沾',
            'em' =>'299.00',
            'img6' => '../images/shop/7-6.jpg',
            'img7' => '../images/shop/7-2.jpg',
            'img8' => '../images/shop/7-3.jpg',
            'img9' => '../images/shop/7-4.jpg',
            'img10' => '../images/shop/7-5.jpg',
            'id' => '7'
        ),
        array(
            'img1' => '../images/shop/9-1.jpg',
            'img2' => '../images/shop/9-2.jpg',
            'img3' => '../images/shop/9-3.jpg',
            'img4' => '../images/shop/9-4.jpg',
            'img5' => '../images/shop/9-5.jpg',
            'h1' => '【直营】highcook韩库进口蓝宝石不粘炒锅无烟电磁炉平底锅30cm',
            'h2' =>'韩国爆款蓝宝石煎炒两用锅 智能控烟真不沾',
            'em' =>'299.00',
            'img6' => '../images/shop/9-1.jpg',
            'img7' => '../images/shop/9-2.jpg',
            'img8' => '../images/shop/9-3.jpg',
            'img9' => '../images/shop/9-4.jpg',
            'img10' => '../images/shop/9-5.jpg',
            'id' => '8'
        ),
        array(
            'img1' => '../images/shop/10-1.jpg',
            'img2' => '../images/shop/10-2.jpg',
            'img3' => '../images/shop/10-3.jpg',
            'img4' => '../images/shop/10-4.jpg',
            'img5' => '../images/shop/10-5.jpg',
            'h1' => '【直营】日本ASVEL保温杯 保温保冷不锈钢内胆带推拉卡扣杯盖手把',
            'h2' =>'韩国爆款蓝宝石煎炒两用锅 智能控烟真不沾',
            'em' =>'198.00',
            'img6' => '../images/shop/10-6.jpg',
            'img7' => '../images/shop/10-7.jpg',
            'img8' => '../images/shop/10-8.jpg',
            'img9' => '../images/shop/10-4.jpg',
            'img10' => '../images/shop/10-5.jpg',
            'id' => '9'
        ),
        array(
            'img1' => '../images/shop/11-1.jpg',
            'img2' => '../images/shop/11-2.jpg',
            'img3' => '../images/shop/11-3.jpg',
            'img4' => '../images/shop/11-4.jpg',
            'img5' => '../images/shop/11-5.jpg',
            'h1' => '【直营】日本进口波佐见烧翔芳窑古染手绘马克杯水杯咖啡杯 360ml',
            'h2' =>'古染釉下彩上色 浓厚和风气息 全手工制作',
            'em' =>'356.00',
            'img6' => '../images/shop/11-6.jpg',
            'img7' => '../images/shop/11-2.jpg',
            'img8' => '../images/shop/11-3.jpg',
            'img9' => '../images/shop/11-4.jpg',
            'img10' => '../images/shop/11-5.jpg',
            'id' => '10'
        ),
        array(
            'img1' => '../images/shop/12-1.jpg',
            'img2' => '../images/shop/12-2.jpg',
            'img3' => '../images/shop/12-3.jpg',
            'img4' => '../images/shop/12-4.jpg',
            'img5' => '../images/shop/12-5.jpg',
            'h1' => '【直营】德国Emsa进口爱慕莎保温壶索菲特不锈钢家庭便携水壶1.5L',
            'h2' =>'双层不锈钢 超大容量 全家用水',
            'em' =>'399.00',
            'img6' => '../images/shop/12-6.jpg',
            'img7' => '../images/shop/12-7.jpg',
            'img8' => '../images/shop/12-8.jpg',
            'img9' => '../images/shop/12-9.jpg',
            'img10' => '../images/shop/12-10.jpg',
            'id' => '11'
        ),
        array(
            'img1' => '../images/shop/13-1.jpg',
            'img2' => '../images/shop/13-2.jpg',
            'img3' => '../images/shop/13-3.jpg',
            'img4' => '../images/shop/13-4.jpg',
            'img5' => '../images/shop/13-5.jpg',
            'h1' => 'cosmic mansion韩国网红 时尚博主热推 精油 香薰蜡烛 香氛礼盒',
            'h2' =>'韩国网红品牌，韩剧同款 精美礼盒 博主主推',
            'em' =>'399.00',
            'img6' => '../images/shop/13-6.jpg',
            'img7' => '../images/shop/13-7.jpg',
            'img8' => '../images/shop/13-8.jpg',
            'img9' => '../images/shop/13-9.jpg',
            'img10' => '../images/shop/13-10.jpg',
            'id' => '12'
        ),
    );
    echo json_encode($data)
?>